const VERSION="4.0.0",KEY="sgo_complete_v4";
const seed={
companies:[{id:"group",code:"SG",name:"Sousa Group",type:"Groupe",employees:18},{id:"electricite",code:"SE",name:"Sousa Électricité",type:"Électricité",employees:9},{id:"home",code:"SHS",name:"Sousa Home Service",type:"Services",employees:6},{id:"tech",code:"ST",name:"Sousa Tech",type:"Informatique",employees:3}],
employees:[
{id:1,name:"Joao Sousa",initials:"JS",job:"Administrateur du groupe",company:"group",email:"joao@sousagroup.ch",phone:"+41 76 688 92 65",salary:8500,activity:100,status:"Présent",hours:42.25,overtime:6.5,vacation:18,entry:"2026-01-01",vehicle:"SG-01"},
{id:2,name:"Sohan De Sousa",initials:"SD",job:"Responsable opérations",company:"home",email:"sohan@sousagroup.ch",phone:"+41 78 205 86 71",salary:7200,activity:100,status:"Chantier",hours:40.5,overtime:3.25,vacation:15,entry:"2026-03-01",vehicle:"SHS-01"},
{id:3,name:"Ana Martins",initials:"AM",job:"Responsable RH",company:"group",email:"ana@sousagroup.ch",phone:"+41 79 111 22 33",salary:6800,activity:100,status:"Télétravail",hours:40,overtime:1,vacation:17,entry:"2026-04-01",vehicle:""},
{id:4,name:"Lucas Moreira",initials:"LM",job:"Électricien CFC",company:"electricite",email:"lucas@sousagroup.ch",phone:"+41 79 222 33 44",salary:6100,activity:100,status:"Chantier",hours:41.08,overtime:3.33,vacation:12,entry:"2026-05-01",vehicle:"SE-02"},
{id:5,name:"Miguel Costa",initials:"MC",job:"Aide-monteur",company:"electricite",email:"miguel@sousagroup.ch",phone:"+41 79 333 44 55",salary:4800,activity:100,status:"Maladie",hours:28.33,overtime:0,vacation:9,entry:"2026-06-01",vehicle:""},
{id:6,name:"Nuno Ferreira",initials:"NF",job:"Technicien informatique",company:"tech",email:"nuno@sousagroup.ch",phone:"+41 79 444 55 66",salary:6600,activity:100,status:"Présent",hours:37.75,overtime:2,vacation:20,entry:"2026-07-01",vehicle:"ST-01"}],
clients:[{id:1,name:"Marie Dupont",type:"Particulier",email:"marie.dupont@email.ch",phone:"+41 79 555 66 77",city:"Lausanne",status:"Actif",projects:1,revenue:12850},{id:2,name:"Régie Arc SA",type:"Entreprise",email:"technique@regie-arc.ch",phone:"+41 21 555 12 12",city:"Morges",status:"Actif",projects:4,revenue:28750},{id:3,name:"Cabinet Nova",type:"Entreprise",email:"direction@cabinetnova.ch",phone:"+41 22 555 13 13",city:"Nyon",status:"Actif",projects:2,revenue:8780},{id:4,name:"Marc Blanc",type:"Particulier",email:"marc.blanc@email.ch",phone:"+41 79 666 77 88",city:"Pully",status:"Prospect",projects:1,revenue:7400}],
projects:[
{id:"SE-2026-0045",company:"electricite",clientId:1,title:"Rénovation électrique appartement",address:"Avenue du Léman 22, Lausanne",team:[4,5],status:"En cours",progress:68,start:"2026-07-20",end:"2026-08-08",budget:12850,cost:7430,hours:54.25,materials:23,photos:14,docs:6,description:"Remplacement du tableau, nouvelles prises, interrupteurs et contrôle final."},
{id:"SHS-2026-0018",company:"home",clientId:4,title:"Remise en état villa",address:"Chemin des Fleurs 8, Pully",team:[2],status:"Planifié",progress:15,start:"2026-08-05",end:"2026-08-14",budget:7400,cost:1120,hours:8,materials:8,photos:5,docs:3,description:"Petite peinture, joints silicone, montage et réparations."},
{id:"ST-2026-0007",company:"tech",clientId:3,title:"Installation réseau & Wi-Fi",address:"Route de Divonne 12, Nyon",team:[6],status:"En cours",progress:42,start:"2026-07-28",end:"2026-08-12",budget:5900,cost:2140,hours:21,materials:11,photos:6,docs:5,description:"Baie réseau, Wi-Fi, VLAN et sécurisation."},
{id:"SE-2026-0042",company:"electricite",clientId:2,title:"Mise aux normes tableau électrique",address:"Rue Centrale 4, Morges",team:[4],status:"À facturer",progress:100,start:"2026-07-14",end:"2026-07-31",budget:8250,cost:4360,hours:31,materials:17,photos:18,docs:7,description:"Remplacement du tableau et contrôle de l’installation."}],
time:[{id:1,date:"2026-08-01",employeeId:4,project:"SE-2026-0045",start:"07:28",break:60,end:"16:42",hours:8.23,status:"Validé"},{id:2,date:"2026-08-01",employeeId:2,project:"SHS-2026-0018",start:"07:55",break:60,end:"17:05",hours:8.17,status:"À vérifier"},{id:3,date:"2026-08-01",employeeId:6,project:"ST-2026-0007",start:"08:02",break:60,end:"16:18",hours:7.27,status:"Validé"},{id:4,date:"2026-07-31",employeeId:4,project:"SE-2026-0042",start:"07:31",break:60,end:"17:00",hours:8.48,status:"Modifié"}],
absences:[{id:1,employeeId:5,type:"Maladie",from:"2026-08-01",to:"2026-08-03",days:3,status:"Justificatif attendu",comment:"Fièvre"},{id:2,employeeId:4,type:"Vacances",from:"2026-08-17",to:"2026-08-28",days:10,status:"Approuvée",comment:"Vacances annuelles"},{id:3,employeeId:6,type:"Vacances",from:"2026-09-07",to:"2026-09-11",days:5,status:"En attente",comment:"Voyage"}],
quotes:[{id:"D-2026-0112",clientId:4,title:"Remise en état villa",amount:7400,status:"Accepté",date:"2026-07-22",valid:"2026-08-21"},{id:"D-2026-0115",clientId:3,title:"Contrat de maintenance informatique",amount:2880,status:"Envoyé",date:"2026-07-30",valid:"2026-08-30"},{id:"D-2026-0117",clientId:2,title:"Éclairage parties communes",amount:14600,status:"Brouillon",date:"2026-08-01",valid:"2026-09-01"}],
invoices:[{id:"F-2026-0088",clientId:2,project:"SE-2026-0042",title:"Mise aux normes tableau",amount:8250,paid:0,status:"À envoyer",date:"2026-08-01",due:"2026-08-12"},{id:"F-2026-0085",clientId:1,project:"SE-2026-0039",title:"Installation luminaires",amount:3480,paid:0,status:"En retard",date:"2026-06-25",due:"2026-07-25"},{id:"F-2026-0084",clientId:3,project:"ST-2026-0007",title:"Acompte réseau",amount:2950,paid:2950,status:"Payée",date:"2026-07-02",due:"2026-08-02"}],
payments:[{id:"P-2026-0061",invoice:"F-2026-0084",clientId:3,amount:2950,date:"2026-07-28",method:"Virement",status:"Confirmé"}],
expenses:[{id:"A-2026-0104",company:"electricite",supplier:"Elektro-Material SA",project:"SE-2026-0045",amount:1260,date:"2026-07-29",category:"Matériel",status:"Validée"},{id:"A-2026-0105",company:"home",supplier:"Hornbach",project:"SHS-2026-0018",amount:438,date:"2026-08-01",category:"Matériel",status:"À valider"},{id:"A-2026-0106",company:"tech",supplier:"Digitec",project:"ST-2026-0007",amount:1290,date:"2026-07-27",category:"Matériel IT",status:"Validée"}],
inventory:[{id:1,sku:"ELEC-CAB-3G15",name:"Câble TT 3x1.5 mm²",category:"Électricité",stock:420,min:150,unit:"m",buy:1.15,sell:2.4,location:"Dépôt A"},{id:2,sku:"ELEC-PRI-T13",name:"Prise T13 blanche",category:"Électricité",stock:38,min:30,unit:"pcs",buy:8.6,sell:19.5,location:"Dépôt A"},{id:3,sku:"HOME-SIL-W",name:"Silicone sanitaire blanc",category:"Maintenance",stock:11,min:12,unit:"pcs",buy:7.2,sell:18,location:"Dépôt B"},{id:4,sku:"IT-AP-U7",name:"Point d’accès Wi-Fi",category:"Informatique",stock:4,min:3,unit:"pcs",buy:168,sell:295,location:"Dépôt C"},{id:5,sku:"PPE-GLOVES",name:"Gants de protection",category:"EPI",stock:7,min:20,unit:"paires",buy:4.5,sell:0,location:"Dépôt A"}],
suppliers:[{id:1,name:"Elektro-Material SA",category:"Électricité",contact:"Service Lausanne",email:"lausanne@em.ch",phone:"+41 21 000 00 01",rating:5,spend:28640},{id:2,name:"Hornbach",category:"Construction",contact:"Service Pro",email:"pro@hornbach.ch",phone:"+41 21 000 00 02",rating:4,spend:9240},{id:3,name:"Digitec",category:"Informatique",contact:"Business",email:"business@digitec.ch",phone:"+41 44 000 00 03",rating:4,spend:12870}],
vehicles:[{id:"SG-01",plate:"VD 123 456",brand:"Mercedes",model:"Vito",company:"group",driver:1,km:68210,status:"Disponible",service:"2026-09-15"},{id:"SE-02",plate:"VD 234 567",brand:"VW",model:"Caddy",company:"electricite",driver:4,km:94880,status:"En service",service:"2026-08-20"},{id:"SHS-01",plate:"VD 345 678",brand:"Ford",model:"Transit",company:"home",driver:2,km:44230,status:"En service",service:"2026-10-01"},{id:"ST-01",plate:"VD 456 789",brand:"Renault",model:"Kangoo E-Tech",company:"tech",driver:6,km:12680,status:"Recharge",service:"2027-01-12"}],
tools:[{id:"OUT-001",name:"Testeur d’installation",category:"Mesure",serial:"FLK-88391",company:"electricite",assigned:4,status:"Attribué",check:"2026-11-30"},{id:"OUT-002",name:"Perceuse Hilti",category:"Électroportatif",serial:"HLT-11882",company:"home",assigned:2,status:"Attribué",check:"2026-12-15"},{id:"OUT-003",name:"Analyseur réseau",category:"Informatique",serial:"NET-99120",company:"tech",assigned:6,status:"Attribué",check:"2027-02-10"}],
maintenance:[{id:"CTR-001",clientId:2,title:"Maintenance électrique immeubles",company:"electricite",frequency:"Trimestrielle",next:"2026-09-10",amount:9600,status:"Actif"},{id:"CTR-002",clientId:3,title:"Maintenance réseau et sauvegardes",company:"tech",frequency:"Mensuelle",next:"2026-08-15",amount:2880,status:"Proposé"},{id:"CTR-003",clientId:4,title:"Entretien résidence secondaire",company:"home",frequency:"Mensuelle",next:"2026-08-20",amount:4200,status:"Actif"}],
messages:[{id:1,sender:"Marie Dupont",kind:"client",text:"Bonjour, pouvez-vous confirmer le passage de l’équipe demain ?",time:"09:12"},{id:2,sender:"Sousa Électricité",kind:"us",text:"Bonjour Mme Dupont, oui, l’intervention est confirmée à 08h00.",time:"09:18"},{id:3,sender:"Marie Dupont",kind:"client",text:"Parfait, merci beaucoup.",time:"09:21"}],
notifications:[{title:"Facture en retard",text:"F-2026-0085 · CHF 3’480",type:"danger",read:false},{title:"Absence à traiter",text:"Certificat de Miguel attendu",type:"warning",read:false},{title:"Stock faible",text:"Gants : 7 paires",type:"warning",read:false},{title:"Nouveau message",text:"Mme Dupont · SE-2026-0045",type:"info",read:false}],
audit:[{date:"02.08.2026 07:28",user:"Joao Sousa",action:"Connexion",object:"Application",detail:"Connexion depuis Lausanne"},{date:"01.08.2026 17:12",user:"Ana Martins",action:"Validation",object:"Pointages",detail:"3 pointages validés"},{date:"01.08.2026 16:48",user:"Lucas Moreira",action:"Ajout",object:"SE-2026-0045",detail:"6 photos ajoutées"}],
ai:[{role:"assistant",text:"Bonjour Joao. Je peux analyser les heures, les stocks, les factures et les chantiers, ou préparer un rapport."}],
clock:{active:false,break:false,project:"SE-2026-0045"},settings:{theme:"dark"}
};
const profiles={admin:{name:"Joao Sousa",role:"Administrateur groupe",avatar:"JS",employeeId:1},direction:{name:"Joao Sousa",role:"Direction",avatar:"JS",employeeId:1},hr:{name:"Ana Martins",role:"Ressources humaines",avatar:"AM",employeeId:3},manager:{name:"Sohan De Sousa",role:"Responsable chantier",avatar:"SD",employeeId:2},accounting:{name:"Ana Martins",role:"Comptabilité",avatar:"AM",employeeId:3},employee:{name:"Lucas Moreira",role:"Salarié · Électricien",avatar:"LM",employeeId:4},client:{name:"Marie Dupont",role:"Cliente",avatar:"MD",clientId:1}};
const fullNav=[["Pilotage",[["dashboard","⌂","Tableau de bord"],["companies","◈","Entreprises"],["reports","◔","Rapports & KPI"]]],["Personnel",[["employees","♟","Salariés"],["time","◷","Heures & pointage"],["planning","▦","Planning"],["absences","☀","Absences & vacances"]]],["Opérations",[["projects","▰","Chantiers"],["clients","◎","Clients & CRM"],["maintenance","↻","Maintenance"],["messages","✉","Messages"],["documents","▤","Documents"]]],["Finance",[["quotes","▧","Devis"],["invoices","▥","Factures"],["payments","₣","Paiements"],["expenses","↘","Achats & dépenses"]]],["Ressources",[["inventory","▦","Stock & matériel"],["suppliers","♧","Fournisseurs"],["vehicles","▱","Véhicules"],["tools","⌁","Outillage"]]],["Futur",[["ai","✦","Assistant IA"],["roadmap","⬡","Versions futures"]]],["Administration",[["security","◇","Sécurité & accès"],["audit","≡","Journal"],["settings","⚙","Paramètres"]]]];
const navs={admin:fullNav,direction:fullNav.filter(x=>x[0]!=="Administration"),hr:[["Pilotage",[["dashboard","⌂","Tableau de bord"],["reports","◔","Rapports RH"]]],["Personnel",[["employees","♟","Salariés"],["time","◷","Heures"],["planning","▦","Planning"],["absences","☀","Absences"],["documents","▤","Documents"]]],["Administration",[["audit","≡","Journal"],["settings","⚙","Paramètres"]]]],manager:[["Pilotage",[["dashboard","⌂","Tableau de bord"],["reports","◔","Rapports"]]],["Équipes",[["employees","♟","Mon équipe"],["time","◷","Heures"],["planning","▦","Planning"],["absences","☀","Absences"]]],["Opérations",[["projects","▰","Chantiers"],["clients","◎","Clients"],["inventory","▦","Matériel"],["vehicles","▱","Véhicules"],["tools","⌁","Outillage"],["messages","✉","Messages"]]]],accounting:[["Pilotage",[["dashboard","⌂","Tableau de bord"],["reports","◔","Rapports"]]],["Finance",[["quotes","▧","Devis"],["invoices","▥","Factures"],["payments","₣","Paiements"],["expenses","↘","Dépenses"],["clients","◎","Clients"]]],["Documents",[["documents","▤","Documents"],["messages","✉","Messages"]]]],employee:[["Mon travail",[["dashboard","⌂","Mon tableau de bord"],["time","◷","Mon pointage"],["planning","▦","Mon planning"],["absences","☀","Mes absences"],["projects","▰","Mes chantiers"],["inventory","▦","Matériel"],["messages","✉","Messages"],["documents","▤","Documents"]]]],client:[["Mon espace",[["dashboard","⌂","Mon espace"],["projects","▰","Mes chantiers"],["quotes","▧","Mes devis"],["invoices","▥","Mes factures"],["messages","✉","Messages"],["documents","▤","Documents"],["maintenance","↻","Contrats"]]]]};
let db=load(),session={role:"direction",page:"dashboard",company:"group"},installPrompt=null;
let authToken=localStorage.getItem("sgo_token")||null;
async function apiLogin(email,password){
  const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});
  const body=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(body.error||"Connexion impossible.");
  return body;
}
async function fetchRemoteState(){
  const r=await fetch("/api/state",{headers:{Authorization:"Bearer "+authToken}});
  if(!r.ok)throw new Error("Impossible de charger les données du serveur.");
  const body=await r.json();
  return body.data;
}
function syncState(){
  if(!authToken)return;
  fetch("/api/state",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+authToken},body:JSON.stringify({data:db})}).catch(()=>{});
}
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.projects)return x}catch(e){}const x=clone(seed);localStorage.setItem(KEY,JSON.stringify(x));return x}function save(){localStorage.setItem(KEY,JSON.stringify(db));syncState()}function reset(){db=clone(seed);save()}function money(n){return new Intl.NumberFormat("fr-CH",{style:"currency",currency:"CHF",maximumFractionDigits:0}).format(+n||0)}function date(s){return s?new Date(s+"T12:00:00").toLocaleDateString("fr-CH"):"—"}function emp(id){return db.employees.find(x=>x.id==id)||{name:"—",initials:"?"}}function cli(id){return db.clients.find(x=>x.id==id)||{name:"—"}}function comp(id){return db.companies.find(x=>x.id===id)||db.companies[0]}function visible(id){return session.company==="group"||session.company===id}
function cls(s=""){s=s.toLowerCase();if(["payée","validé","confirmé","accepté","approuv","présent","actif","disponible","terminé"].some(x=>s.includes(x)))return"success";if(["retard","maladie","bloqué","refusé"].some(x=>s.includes(x)))return"danger";if(["attente","planifié","envoyé","à envoyer","à valider","proposé","recharge"].some(x=>s.includes(x)))return"warning";if(["cours","chantier","télétravail","service"].some(x=>s.includes(x)))return"info";if(["brouillon","interne"].some(x=>s.includes(x)))return"purple";return"neutral"}function status(s){return `<span class="status ${cls(s)}">${s}</span>`}function kpi(l,v,s,i){return `<article class="card kpi"><div class="kpi-top"><span>${l}</span><b>${i}</b></div><div class="kpi-value">${v}</div><div class="kpi-sub">${s}</div></article>`}function mini(l,v){return `<div class="mini"><span>${l}</span><b>${v}</b></div>`}function section(t,d,a=""){return `<div class="section-head"><div><h3>${t}</h3><p class="muted">${d}</p></div><div class="actions">${a}</div></div>`}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.add("hidden"),2500)}function audit(action,object,detail){db.audit.unshift({date:new Date().toLocaleString("fr-CH"),user:profiles[session.role].name,action,object,detail});save()}function modal(t,h){document.getElementById("modalTitle").textContent=t;document.getElementById("modalBody").innerHTML=h;document.getElementById("modalWrap").classList.remove("hidden")}function closeModal(){document.getElementById("modalWrap").classList.add("hidden")}function val(id){return document.getElementById(id)?.value?.trim()||""}function download(n,t,type="text/plain"){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}function csv(r){return r.map(x=>x.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n")}
function field(l,id,type="text",value="",full=false,opts=null){if(opts)return `<label class="${full?"full":""}">${l}<select id="${id}">${opts.map(o=>`<option value="${o.value}">${o.label}</option>`).join("")}</select></label>`;return `<label class="${full?"full":""}">${l}<input id="${id}" type="${type}" value="${value}"></label>`}function area(l,id){return `<label class="full">${l}<textarea id="${id}" rows="4"></textarea></label>`}function formBtns(action){return `<div class="form-actions"><button class="btn ghost" onclick="closeModal()">Annuler</button><button class="btn primary" onclick="${action}">Enregistrer</button></div>`}

document.getElementById("loginRole").onchange=()=>{const r=document.getElementById("loginRole").value;document.getElementById("loginEmail").value=r+"@sousagroup.ch";document.getElementById("loginPassword").value="demo1234"};
document.getElementById("loginBtn").onclick=async()=>{
  const email=document.getElementById("loginEmail").value.trim();
  const password=document.getElementById("loginPassword").value;
  const errEl=document.getElementById("loginError");
  errEl.style.display="none";
  const btn=document.getElementById("loginBtn");
  btn.disabled=true;btn.textContent="Connexion…";
  try{
    const {token,profile}=await apiLogin(email,password);
    authToken=token;localStorage.setItem("sgo_token",token);
    session.role=profile.role;session.company=profile.company;session.page="dashboard";session.profile=profile;
    try{const remote=await fetchRemoteState();if(remote){db=remote}else{save()}}catch(e){}
    document.getElementById("login").classList.add("hidden");
    document.getElementById("app").classList.remove("hidden");
    audit("Connexion","Application",profile.role);
    shell();
    toast("Bienvenue dans Sousa Group One");
  }catch(e){
    errEl.textContent=e.message||"Connexion impossible.";
    errEl.style.display="block";
  }finally{
    btn.disabled=false;btn.textContent="Accéder à l’application";
  }
};
document.getElementById("resetLogin").onclick=()=>{reset();toast("Démonstration réinitialisée pour tout le monde")};
document.getElementById("logoutBtn").onclick=()=>{authToken=null;localStorage.removeItem("sgo_token");document.getElementById("app").classList.add("hidden");document.getElementById("login").classList.remove("hidden")};
document.getElementById("themeBtn").onclick=()=>{db.settings.theme=db.settings.theme==="dark"?"light":"dark";save();theme()};
document.getElementById("notifBtn").onclick=showNotifications;
document.getElementById("closeModal").onclick=closeModal;document.getElementById("modalWrap").onclick=e=>{if(e.target.id==="modalWrap")closeModal()};
document.getElementById("companyFilter").onchange=e=>{session.company=e.target.value;render();toast("Vue : "+comp(session.company).name)};
document.getElementById("openSide").onclick=()=>side(true);document.getElementById("closeSide").onclick=()=>side(false);document.getElementById("backdrop").onclick=()=>side(false);
document.getElementById("search").oninput=e=>search(e.target.value);document.getElementById("importFile").onchange=importBackup;
function side(open){document.getElementById("sidebar").classList.toggle("open",open);document.getElementById("backdrop").classList.toggle("hidden",!open)}
function theme(){document.body.classList.toggle("light",db.settings.theme==="light")}
function shell(){const p=session.profile||profiles[session.role];document.getElementById("userName").textContent=p.name;document.getElementById("userRole").textContent=p.role;document.getElementById("avatar").textContent=p.avatar;document.getElementById("companyFilter").innerHTML=db.companies.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");document.getElementById("companyFilter").value=session.company;document.getElementById("companyFilter").disabled=session.role==="client";nav();theme();render()}
function nav(){document.getElementById("nav").innerHTML=navs[session.role].map(([g,items])=>`<div class="nav-group">${g}</div>${items.map(([id,ic,l])=>`<button class="nav-item ${session.page===id?"active":""}" data-page="${id}"><i>${ic}</i><span>${l}</span></button>`).join("")}`).join("");document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{session.page=b.dataset.page;nav();render();side(false)})}
function render(){const names={dashboard:"Tableau de bord",companies:"Entreprises du groupe",reports:"Rapports & indicateurs",employees:"Salariés",time:"Heures & pointage",planning:"Planning",absences:"Absences & vacances",projects:"Chantiers",clients:"Clients & CRM",maintenance:"Maintenance & contrats",messages:"Messages",documents:"Documents",quotes:"Devis",invoices:"Factures",payments:"Paiements",expenses:"Achats & dépenses",inventory:"Stock & matériel",suppliers:"Fournisseurs",vehicles:"Véhicules",tools:"Outillage",ai:"Assistant IA",roadmap:"Versions futures",security:"Sécurité & accès",audit:"Journal d’activité",settings:"Paramètres"};document.getElementById("title").textContent=names[session.page]||"Sousa Group One";document.getElementById("crumb").textContent=`SOUSA GROUP ONE · ${profiles[session.role].role.toUpperCase()} · V${VERSION}`;document.getElementById("content").innerHTML=(pages[session.page]||pages.dashboard)();bind();charts();document.getElementById("notifCount").textContent=db.notifications.filter(n=>!n.read).length}
function bind(){document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());document.querySelectorAll("[data-project]").forEach(b=>b.onclick=()=>openProject(b.dataset.project));document.querySelectorAll("[data-employee]").forEach(b=>b.onclick=()=>openEmployee(+b.dataset.employee));document.querySelectorAll("[data-client]").forEach(b=>b.onclick=()=>openClient(+b.dataset.client));document.querySelectorAll("[data-doc]").forEach(b=>b.onclick=()=>openDoc(b.dataset.doc,b.dataset.kind));document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast("Filtre appliqué")});if(document.getElementById("liveClock"))clock()}
function search(q){document.querySelector(".search-results")?.remove();q=q.trim().toLowerCase();if(q.length<2)return;const r=[...db.employees.filter(x=>x.name.toLowerCase().includes(q)).map(x=>({t:x.name,s:x.job,p:"employees"})),...db.clients.filter(x=>x.name.toLowerCase().includes(q)).map(x=>({t:x.name,s:x.city,p:"clients"})),...db.projects.filter(x=>(x.id+" "+x.title).toLowerCase().includes(q)).map(x=>({t:x.id,s:x.title,p:"projects"})),...db.invoices.filter(x=>x.id.toLowerCase().includes(q)).map(x=>({t:x.id,s:money(x.amount),p:"invoices"}))].slice(0,8);const box=document.createElement("div");box.className="search-results";box.innerHTML=r.length?r.map(x=>`<div class="result" data-result="${x.p}"><b>${x.t}</b><span>${x.s}</span></div>`).join(""):`<div class="result">Aucun résultat</div>`;document.body.appendChild(box);box.querySelectorAll("[data-result]").forEach(x=>x.onclick=()=>{session.page=x.dataset.result;nav();render();box.remove();document.getElementById("search").value=""})}
function showNotifications(){modal("Notifications",`<div class="list">${db.notifications.map(n=>`<div class="list-row"><div><b>${n.title}</b><small>${n.text}</small></div>${status(n.type==="danger"?"Urgent":n.type==="warning"?"À traiter":"Information")}</div>`).join("")}</div><div class="form-actions"><button class="btn primary" onclick="readNotifications()">Tout marquer comme lu</button></div>`)}
function readNotifications(){db.notifications.forEach(n=>n.read=true);save();closeModal();render();toast("Notifications lues")}
function charts(){document.querySelectorAll("canvas[data-chart]").forEach(c=>{const ctx=c.getContext("2d"),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);const css=getComputedStyle(document.body),border=css.getPropertyValue("--border"),muted=css.getPropertyValue("--muted"),green=css.getPropertyValue("--green"),blue=css.getPropertyValue("--blue"),yellow=css.getPropertyValue("--yellow");ctx.font="11px system-ui";ctx.strokeStyle=border;ctx.fillStyle=muted;for(let i=0;i<5;i++){let y=20+i*(h-50)/4;ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(w-10,y);ctx.stroke()}let vals,labels,color;if(c.dataset.chart==="revenue"){vals=[31,38,42,46,53,59,64,72];labels=["Jan","Fév","Mar","Avr","Mai","Juin","Juil","Août"];color=green}else if(c.dataset.chart==="hours"){vals=[420,455,470,448,512,536,498,523];labels=["S1","S2","S3","S4","S5","S6","S7","S8"];color=blue}else{vals=[12,18,15,26,22,31,28,36];labels=["Jan","Fév","Mar","Avr","Mai","Juin","Juil","Août"];color=yellow}const max=Math.max(...vals)*1.15,step=(w-55)/(vals.length-1);ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{let x=35+i*step,y=h-30-(v/max)*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();vals.forEach((v,i)=>{let x=35+i*step,y=h-30-(v/max)*(h-60);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillStyle=muted;ctx.fillText(labels[i],x-10,h-9)})})}
function projectRow(p){return `<div style="padding:12px 0;border-bottom:1px solid var(--border)"><div style="display:flex;justify-content:space-between;gap:10px;margin-bottom:8px"><div><b style="font-size:.73rem">${p.id} · ${cli(p.clientId).name}</b><div class="muted" style="font-size:.62rem;margin-top:3px">${p.title}</div></div>${status(p.status)}</div><div class="progress"><span style="width:${p.progress}%"></span></div><div class="progress-meta"><span>${p.progress} %</span><span>${p.hours} h</span></div></div>`}
function projectCard(p){return `<article class="card project"><div class="project-top"><div><div class="project-code">${p.id}</div><h3>${p.title}</h3><p>${cli(p.clientId).name} · ${p.address}</p></div>${status(p.status)}</div><div class="progress"><span style="width:${p.progress}%"></span></div><div class="progress-meta"><span>${p.progress} % terminé</span><span>${comp(p.company).name}</span></div><div class="mini-grid">${mini("Heures",p.hours+" h")}${mini("Budget",money(p.budget))}${mini("Matériel",p.materials+" articles")}${mini("Photos",p.photos+" fichiers")}</div><button class="btn secondary wide" data-project="${p.id}">Ouvrir</button></article>`}
function timeTable(admin=true){return `<article class="card"><div class="table"><table><thead><tr><th>Date</th>${admin?"<th>Salarié</th>":""}<th>Chantier</th><th>Entrée</th><th>Pause</th><th>Sortie</th><th>Total</th><th>Statut</th></tr></thead><tbody>${db.time.map(t=>`<tr><td>${date(t.date)}</td>${admin?`<td>${emp(t.employeeId).name}</td>`:""}<td>${t.project}</td><td>${t.start}</td><td>${t.break} min</td><td>${t.end}</td><td><b>${t.hours.toFixed(2)} h</b></td><td>${status(t.status)}</td></tr>`).join("")}</tbody></table></div></article>`}
function clockBox(){return `${status(db.clock.active?"En service":"Hors service")}<div id="liveClock" class="clock-time">--:--:--</div><div class="clock-date">${new Date().toLocaleDateString("fr-CH",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</div><label>Chantier<select id="clockProject">${db.projects.slice(0,3).map(p=>`<option value="${p.id}">${p.id} · ${cli(p.clientId).name}</option>`).join("")}</select></label><div class="clock-actions"><button class="btn ${db.clock.active?"danger":"primary"}" data-action="clock">${db.clock.active?"Terminer":"Commencer"}</button><button class="btn secondary" data-action="break">${db.clock.break?"Reprendre":"Pause"}</button></div>`}
function clock(){const e=document.getElementById("liveClock");if(!e)return;const t=()=>{if(document.body.contains(e))e.textContent=new Date().toLocaleTimeString("fr-CH")};t();setInterval(t,1000)}

const pages={
dashboard(){if(session.role==="employee")return employeeDash();if(session.role==="client")return clientDash();let ps=db.projects.filter(p=>visible(p.company));return `<div class="grid g4 section">${kpi("Salariés actifs",db.employees.length,"4 entreprises","♟")}${kpi("Heures semaine","512 h","+6,4 %","◷")}${kpi("Chantiers ouverts",ps.length,"3 échéances","▰")}${kpi("CA encaissé",money(db.invoices.reduce((a,b)=>a+b.paid,0)),"Ce mois","₣")}</div><div class="grid g3 section"><article class="card" style="grid-column:span 2"><div class="card-head"><h3>Évolution du chiffre d’affaires</h3><button class="btn small secondary" data-action="export-report">Exporter</button></div><canvas class="chart" data-chart="revenue"></canvas></article><article class="card"><div class="card-head"><h3>Alertes</h3>${status("4 actions")}</div><div class="timeline">${db.notifications.map(n=>`<div class="tl"><span class="dot"></span><div><b>${n.title}</b><p>${n.text}</p></div></div>`).join("")}</div></article></div><div class="grid g2"><article class="card"><div class="card-head"><h3>Chantiers prioritaires</h3><button class="btn small secondary" onclick="session.page='projects';nav();render()">Voir tout</button></div>${ps.slice(0,4).map(projectRow).join("")}</article><article class="card"><div class="card-head"><h3>Actions rapides</h3></div><div class="quick"><button data-action="new-project"><b>+ Chantier</b><span>Créer un dossier</span></button><button data-action="new-quote"><b>+ Devis</b><span>Préparer une offre</span></button><button data-action="new-invoice"><b>+ Facture</b><span>Facturer</span></button><button data-action="new-employee"><b>+ Salarié</b><span>Créer une fiche</span></button><button data-action="new-expense"><b>+ Dépense</b><span>Ajouter un achat</span></button><button onclick="session.page='ai';nav();render()"><b>✦ Assistant IA</b><span>Analyser et rédiger</span></button></div></article></div>`},
companies(){return `${section("Structure de Sousa Group","Vue consolidée des sociétés.",`<button class="btn primary" data-action="new-company">+ Entreprise</button>`)}<div class="grid g4 section">${db.companies.map(c=>kpi(c.name,c.employees+" pers.",c.type,c.code)).join("")}</div><div class="grid g2">${db.companies.map(c=>{let ps=db.projects.filter(p=>p.company===c.id),rev=db.invoices.filter(i=>ps.some(p=>p.id===i.project)).reduce((a,b)=>a+b.amount,0);return `<article class="card"><div class="card-head"><div><p class="eyebrow">${c.code}</p><h3>${c.name}</h3></div>${status("Active")}</div><div class="mini-grid">${mini("Collaborateurs",c.employees)}${mini("Chantiers",ps.length)}${mini("Facturation",money(rev))}${mini("Secteur",c.type)}</div></article>`}).join("")}</div>`},
reports(){let profit=db.projects.reduce((a,p)=>a+p.budget-p.cost,0);return `${section("Rapports consolidés","Performance financière, humaine et opérationnelle.",`<button class="btn secondary" data-action="export-report">Exporter CSV</button><button class="btn primary" onclick="window.print()">Imprimer</button>`)}<div class="grid g4 section">${kpi("Marge chantiers",money(profit),"Coûts directs déduits","↗")}${kpi("Taux de facturation","86 %","+4 points","▥")}${kpi("Occupation équipes","91 %","Capacité planifiée","♟")}${kpi("Satisfaction","4,8 / 5","37 évaluations","★")}</div><div class="grid g2 section"><article class="card"><div class="card-head"><h3>Heures produites</h3></div><canvas class="chart" data-chart="hours"></canvas></article><article class="card"><div class="card-head"><h3>Marge mensuelle</h3></div><canvas class="chart" data-chart="margin"></canvas></article></div><article class="card"><div class="table"><table><thead><tr><th>Chantier</th><th>Entreprise</th><th>Budget</th><th>Coût</th><th>Marge</th><th>Taux</th></tr></thead><tbody>${db.projects.filter(p=>visible(p.company)).map(p=>`<tr><td><b>${p.id}</b><br><span class="muted">${p.title}</span></td><td>${comp(p.company).name}</td><td>${money(p.budget)}</td><td>${money(p.cost)}</td><td><b>${money(p.budget-p.cost)}</b></td><td>${Math.round((p.budget-p.cost)/p.budget*100)} %</td></tr>`).join("")}</tbody></table></div></article>`},
employees(){let l=db.employees.filter(e=>visible(e.company));return `${section("Fiches salariés","Contrats, heures, vacances et affectations.",`<button class="btn secondary" data-action="export-employees">Exporter</button><button class="btn primary" data-action="new-employee">+ Salarié</button>`)}<div class="grid g4 section">${kpi("Effectif",l.length,"Collaborateurs visibles","♟")}${kpi("Présents",l.filter(e=>e.status!=="Maladie").length,"Aujourd’hui","✓")}${kpi("Vacances",l.reduce((a,b)=>a+b.vacation,0)+" j","Solde cumulé","☀")}${kpi("Heures sup.",l.reduce((a,b)=>a+b.overtime,0).toFixed(1)+" h","Solde actuel","＋")}</div><article class="card"><div class="table"><table><thead><tr><th>Collaborateur</th><th>Fonction</th><th>Entreprise</th><th>Activité</th><th>Heures</th><th>Vacances</th><th>Statut</th><th></th></tr></thead><tbody>${l.map(e=>`<tr><td><b>${e.name}</b><br><span class="muted">${e.email}</span></td><td>${e.job}</td><td>${comp(e.company).name}</td><td>${e.activity} %</td><td>${e.hours} h</td><td>${e.vacation} j</td><td>${status(e.status)}</td><td><button class="btn small secondary" data-employee="${e.id}">Ouvrir</button></td></tr>`).join("")}</tbody></table></div></article>`},
time(){if(session.role==="employee")return `<div class="grid g2 section"><article class="card clock">${clockBox()}</article><article class="card"><div class="card-head"><h3>Résumé mensuel</h3></div><div class="mini-grid">${mini("Heures normales","162 h 30")}${mini("Heures supplémentaires","12 h 20")}${mini("Pauses","4 h")}${mini("Chantiers","3")}</div></article></div>${timeTable(false)}`;return `${section("Suivi des heures","Validation et imputation par chantier.",`<button class="btn secondary" data-action="export-time">Exporter</button><button class="btn primary" data-action="approve-time">Valider la semaine</button>`)}<div class="grid g4 section">${kpi("Heures aujourd’hui","103 h","11 actifs","◷")}${kpi("À valider","18 h","3 modifications","!")}${kpi("Heures sup.","36 h","Solde du mois","＋")}${kpi("Coût estimé",money(7930),"Main-d’œuvre","₣")}</div>${timeTable(true)}`},
planning(){let d=[["Lun. 3","SE-2026-0045 · 08h","Dépôt · 16h30"],["Mar. 4","SE-2026-0045 · 08h","Régie Arc · 14h"],["Mer. 5","SHS-2026-0018 · 07h30",""],["Jeu. 6","ST-2026-0007 · 08h","Réunion · 16h"],["Ven. 7","SE-2026-0045 · 08h","Contrôle · 14h"],["Sam. 8","Astreinte · 08h",""],["Dim. 9","",""]];return `${section("Planning des équipes","Semaine du 3 au 9 août 2026.",`<button class="btn secondary" data-action="export-planning">Exporter</button><button class="btn primary" data-action="new-planning">+ Planifier</button>`)}<article class="card section"><div class="calendar">${["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"].map(x=>`<div class="cal-head">${x}</div>`).join("")}${d.map((x,i)=>`<div class="day"><span>${x[0]}</span>${x[1]?`<div class="event ${i%3===1?"blue":i%3===2?"yellow":""}">${x[1]}</div>`:""}${x[2]?`<div class="event blue">${x[2]}</div>`:""}</div>`).join("")}</div></article><article class="card"><div class="table"><table><thead><tr><th>Collaborateur</th><th>Lundi</th><th>Mardi</th><th>Mercredi</th><th>Jeudi</th><th>Vendredi</th></tr></thead><tbody>${db.employees.map((e,i)=>`<tr><td><b>${e.name}</b></td>${[1,2,3,4,5].map(j=>`<td>${status(i===4&&j===3?"Congé":"Disponible")}</td>`).join("")}</tr>`).join("")}</tbody></table></div></article>`},
absences(){let l=session.role==="employee"?db.absences.filter(a=>a.employeeId===profiles.employee.employeeId):db.absences;return `${section(session.role==="employee"?"Mes absences":"Absences et vacances","Demandes, validations et justificatifs.",`<button class="btn primary" data-action="new-absence">+ Demande</button>`)}<div class="grid g4 section">${kpi("Vacances restantes",session.role==="employee"?"12 j":"91 j","Solde","☀")}${kpi("En attente",l.filter(a=>a.status==="En attente").length,"À traiter","…")}${kpi("Absents","1","Aujourd’hui","☂")}${kpi("Congés à venir","2","30 jours","▦")}</div><article class="card"><div class="table"><table><thead><tr><th>Salarié</th><th>Type</th><th>Période</th><th>Jours</th><th>Commentaire</th><th>Statut</th><th></th></tr></thead><tbody>${l.map(a=>`<tr><td>${emp(a.employeeId).name}</td><td>${a.type}</td><td>${date(a.from)} – ${date(a.to)}</td><td>${a.days}</td><td>${a.comment}</td><td>${status(a.status)}</td><td>${session.role!=="employee"?`<button class="btn small secondary" onclick="approveAbsence(${a.id})">Traiter</button>`:""}</td></tr>`).join("")}</tbody></table></div></article>`},
projects(){let l=db.projects.filter(p=>visible(p.company));if(session.role==="client")l=l.filter(p=>p.clientId===1);if(session.role==="employee")l=l.filter(p=>p.team.includes(4));return `${section(session.role==="client"?"Mes chantiers":"Gestion des chantiers","Heures, matériel, photos, documents, coûts et messages.",session.role==="client"?"":`<button class="btn secondary" data-action="export-projects">Exporter</button><button class="btn primary" data-action="new-project">+ Chantier</button>`)}<div class="tabs"><button class="tab active" data-tab>Tous</button><button class="tab" data-tab>En cours</button><button class="tab" data-tab>Planifiés</button><button class="tab" data-tab>À facturer</button></div><div class="grid g2">${l.map(projectCard).join("")}</div>`},
clients(){return `${section("Clients & CRM","Contacts, historique, opportunités et chiffre d’affaires.",`<button class="btn secondary" data-action="export-clients">Exporter</button><button class="btn primary" data-action="new-client">+ Client</button>`)}<div class="grid g4 section">${kpi("Clients actifs","3","Portefeuille","◎")}${kpi("Prospects","1","À relancer","↗")}${kpi("CA portefeuille",money(db.clients.reduce((a,b)=>a+b.revenue,0)),"Cumulé","₣")}${kpi("Satisfaction","4,8 / 5","37 avis","★")}</div><article class="card"><div class="table"><table><thead><tr><th>Client</th><th>Type</th><th>Ville</th><th>Coordonnées</th><th>Chantiers</th><th>CA</th><th>Statut</th><th></th></tr></thead><tbody>${db.clients.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.type}</td><td>${c.city}</td><td>${c.email}<br>${c.phone}</td><td>${c.projects}</td><td>${money(c.revenue)}</td><td>${status(c.status)}</td><td><button class="btn small secondary" data-client="${c.id}">Ouvrir</button></td></tr>`).join("")}</tbody></table></div></article>`},
maintenance(){let l=db.maintenance.filter(m=>visible(m.company));if(session.role==="client")l=l.filter(m=>m.clientId===1);return `${section(session.role==="client"?"Mes contrats":"Maintenance récurrente","Interventions planifiées et renouvellements.",session.role==="client"?"":`<button class="btn primary" data-action="new-maintenance">+ Contrat</button>`)}<div class="grid g3">${l.map(m=>`<article class="card"><div class="card-head"><div><p class="eyebrow">${m.id}</p><h3>${m.title}</h3></div>${status(m.status)}</div><div class="mini-grid">${mini("Client",cli(m.clientId).name)}${mini("Fréquence",m.frequency)}${mini("Prochaine visite",date(m.next))}${mini("Valeur annuelle",money(m.amount))}</div></article>`).join("")}</div>`},
messages(){return `<article class="card chat"><aside class="chat-list"><div class="card-head"><h3>Conversations</h3><button class="btn small primary">+</button></div><div class="chat-item active"><b>Marie Dupont</b><span>SE-2026-0045 · 12 min</span></div><div class="chat-item"><b>Régie Arc SA</b><span>SE-2026-0042 · hier</span></div><div class="chat-item"><b>Équipe interne</b><span>Hier</span></div><div class="chat-item"><b>Cabinet Nova</b><span>Lundi</span></div></aside><section class="chat-main"><div class="card-head"><div><h3>Marie Dupont</h3><span class="muted">SE-2026-0045</span></div>${status("Client")}</div><div class="messages">${db.messages.map(m=>`<div class="message ${m.kind==="us"?"mine":""}">${m.text}<small>${m.sender} · ${m.time}</small></div>`).join("")}</div><div class="composer"><input id="messageText" placeholder="Écrire un message…"><button class="btn primary" data-action="send-message">Envoyer</button></div></section></article>`},
documents(){let docs=[["Contrats de travail","18 fichiers","RH"],["Devis et factures","42 fichiers","Finance"],["Rapports de chantier","31 fichiers","Opérations"],["Photos de chantier","126 fichiers","Opérations"],["Certificats","22 fichiers","RH"],["Conditions générales","4 fichiers","Groupe"]];return `${section(session.role==="client"?"Mes documents":"Gestion documentaire","Classement sécurisé, versions et signatures.",`<button class="btn secondary" data-action="backup">Sauvegarder</button><button class="btn primary">+ Document</button>`)}<div class="grid g3">${docs.map(d=>`<article class="card"><div class="card-head"><span style="font-size:1.5rem">▤</span>${status(d[2])}</div><h3>${d[0]}</h3><p class="muted" style="font-size:.7rem;margin:7px 0 15px">${d[1]}</p><button class="btn secondary wide">Ouvrir</button></article>`).join("")}</div>`},
quotes(){let l=session.role==="client"?db.quotes.filter(q=>q.clientId===1):db.quotes;return `${section(session.role==="client"?"Mes devis":"Gestion des devis","Envoi, acceptation et transformation en chantier.",session.role==="client"?"":`<button class="btn secondary" data-action="export-quotes">Exporter</button><button class="btn primary" data-action="new-quote">+ Devis</button>`)}<article class="card"><div class="table"><table><thead><tr><th>N°</th><th>Client</th><th>Objet</th><th>Date</th><th>Validité</th><th>Montant</th><th>Statut</th><th></th></tr></thead><tbody>${l.map(q=>`<tr><td><b>${q.id}</b></td><td>${cli(q.clientId).name}</td><td>${q.title}</td><td>${date(q.date)}</td><td>${date(q.valid)}</td><td><b>${money(q.amount)}</b></td><td>${status(q.status)}</td><td><button class="btn small secondary" data-doc="${q.id}" data-kind="quote">Ouvrir</button></td></tr>`).join("")}</tbody></table></div></article>`},
invoices(){let l=session.role==="client"?db.invoices.filter(i=>i.clientId===1):db.invoices;return `${section(session.role==="client"?"Mes factures":"Gestion des factures","Acomptes, paiements, rappels et échéances.",session.role==="client"?"":`<button class="btn secondary" data-action="export-invoices">Exporter</button><button class="btn primary" data-action="new-invoice">+ Facture</button>`)}<div class="grid g4 section">${kpi("À facturer",money(8250),"Chantiers terminés","▥")}${kpi("En retard",money(3480),"À relancer","!")}${kpi("Payé",money(db.invoices.reduce((a,b)=>a+b.paid,0)),"Encaissements","✓")}${kpi("Délai moyen","18 jours","Paiement","◷")}</div><article class="card"><div class="table"><table><thead><tr><th>Facture</th><th>Client</th><th>Chantier</th><th>Échéance</th><th>Montant</th><th>Payé</th><th>Statut</th><th></th></tr></thead><tbody>${l.map(i=>`<tr><td><b>${i.id}</b></td><td>${cli(i.clientId).name}</td><td>${i.project}</td><td>${date(i.due)}</td><td><b>${money(i.amount)}</b></td><td>${money(i.paid)}</td><td>${status(i.status)}</td><td><button class="btn small secondary" data-doc="${i.id}" data-kind="invoice">Ouvrir</button></td></tr>`).join("")}</tbody></table></div></article>`},
payments(){return `${section("Paiements","Encaissements, acomptes et rapprochement.",`<button class="btn primary" data-action="new-payment">+ Paiement</button>`)}<div class="grid g4 section">${kpi("Encaissé",money(58920),"+14 %","₣")}${kpi("À recevoir",money(11730),"Factures ouvertes","↘")}${kpi("Acomptes",money(12400),"5 chantiers","▥")}${kpi("Taux paiement","92 %","Dans les délais","✓")}</div><article class="card"><div class="table"><table><thead><tr><th>Paiement</th><th>Facture</th><th>Client</th><th>Date</th><th>Mode</th><th>Montant</th><th>Statut</th></tr></thead><tbody>${db.payments.map(p=>`<tr><td><b>${p.id}</b></td><td>${p.invoice}</td><td>${cli(p.clientId).name}</td><td>${date(p.date)}</td><td>${p.method}</td><td><b>${money(p.amount)}</b></td><td>${status(p.status)}</td></tr>`).join("")}</tbody></table></div></article>`},
expenses(){return `${section("Achats et dépenses","Justificatifs, validation et imputation.",`<button class="btn secondary" data-action="export-expenses">Exporter</button><button class="btn primary" data-action="new-expense">+ Dépense</button>`)}<div class="grid g4 section">${kpi("Dépenses",money(db.expenses.reduce((a,b)=>a+b.amount,0)),"Ce mois","↘")}${kpi("À valider","1","Justificatif","…")}${kpi("Matériel",money(2988),"Coûts directs","▦")}${kpi("Fournisseurs",db.suppliers.length,"Actifs","♧")}</div><article class="card"><div class="table"><table><thead><tr><th>Référence</th><th>Date</th><th>Fournisseur</th><th>Entreprise</th><th>Chantier</th><th>Montant</th><th>Statut</th></tr></thead><tbody>${db.expenses.filter(e=>visible(e.company)).map(e=>`<tr><td><b>${e.id}</b></td><td>${date(e.date)}</td><td>${e.supplier}</td><td>${comp(e.company).name}</td><td>${e.project}</td><td><b>${money(e.amount)}</b></td><td>${status(e.status)}</td></tr>`).join("")}</tbody></table></div></article>`},
inventory(){let l=db.inventory;return `${section("Stock et matériel","Niveaux, mouvements, alertes et valorisation.",`<button class="btn secondary" data-action="export-stock">Exporter</button><button class="btn primary" data-action="new-stock">+ Article</button>`)}<div class="grid g4 section">${kpi("Références",l.length,"Articles suivis","▦")}${kpi("Valeur stock",money(l.reduce((a,b)=>a+b.stock*b.buy,0)),"Prix d’achat","₣")}${kpi("Stocks faibles",l.filter(x=>x.stock<=x.min).length,"À commander","!")}${kpi("Mouvements","128","Ce mois","↔")}</div><article class="card"><div class="table"><table><thead><tr><th>Référence</th><th>Article</th><th>Catégorie</th><th>Stock</th><th>Minimum</th><th>Achat</th><th>Vente</th><th>Emplacement</th><th>État</th></tr></thead><tbody>${l.map(x=>`<tr><td><b>${x.sku}</b></td><td>${x.name}</td><td>${x.category}</td><td><b>${x.stock} ${x.unit}</b></td><td>${x.min} ${x.unit}</td><td>${money(x.buy)}</td><td>${money(x.sell)}</td><td>${x.location}</td><td>${status(x.stock<=x.min?"Stock faible":"Disponible")}</td></tr>`).join("")}</tbody></table></div></article>`},
suppliers(){return `${section("Fournisseurs","Contacts, dépenses et performance.",`<button class="btn primary" data-action="new-supplier">+ Fournisseur</button>`)}<div class="grid g3">${db.suppliers.map(s=>`<article class="card"><div class="card-head"><div><p class="eyebrow">${s.category}</p><h3>${s.name}</h3></div><span>${"★".repeat(s.rating)}${"☆".repeat(5-s.rating)}</span></div><div class="mini-grid">${mini("Contact",s.contact)}${mini("Dépenses",money(s.spend))}${mini("E-mail",s.email)}${mini("Téléphone",s.phone)}</div></article>`).join("")}</div>`},
vehicles(){return `${section("Parc de véhicules","Affectations, kilométrage et entretiens.",`<button class="btn primary" data-action="new-vehicle">+ Véhicule</button>`)}<div class="grid g2">${db.vehicles.filter(v=>visible(v.company)).map(v=>`<article class="card"><div class="card-head"><div><p class="eyebrow">${v.id} · ${v.plate}</p><h3>${v.brand} ${v.model}</h3></div>${status(v.status)}</div><div class="mini-grid">${mini("Entreprise",comp(v.company).name)}${mini("Conducteur",emp(v.driver).name)}${mini("Kilométrage",v.km.toLocaleString("fr-CH")+" km")}${mini("Prochain service",date(v.service))}</div></article>`).join("")}</div>`},
tools(){return `${section("Outillage","Attribution, contrôles et inventaire.",`<button class="btn primary" data-action="new-tool">+ Outil</button>`)}<article class="card"><div class="table"><table><thead><tr><th>Référence</th><th>Équipement</th><th>Catégorie</th><th>N° série</th><th>Entreprise</th><th>Attribué à</th><th>Contrôle</th><th>Statut</th></tr></thead><tbody>${db.tools.filter(t=>visible(t.company)).map(t=>`<tr><td><b>${t.id}</b></td><td>${t.name}</td><td>${t.category}</td><td>${t.serial}</td><td>${comp(t.company).name}</td><td>${emp(t.assigned).name}</td><td>${date(t.check)}</td><td>${status(t.status)}</td></tr>`).join("")}</tbody></table></div></article>`},
ai(){return `${section("Assistant IA Sousa","Analyse, rédaction, alertes et rapports.","")}<div class="ai"><article class="card ai-chat"><div class="ai-msgs" id="aiMsgs">${db.ai.map(m=>`<div class="ai-bubble ${m.role==="user"?"user":""}">${m.text}</div>`).join("")}</div><div class="composer"><input id="aiInput" placeholder="Ex. Résume le chantier SE-2026-0045"><button class="btn primary" data-action="ask-ai">Envoyer</button></div></article><aside class="card ai-prompts"><div class="card-head"><h3>Suggestions</h3></div>${["Analyse les stocks faibles","Résume le chantier SE-2026-0045","Factures à relancer","Analyse les heures supplémentaires","Prépare un rapport client"].map(x=>`<button class="btn secondary" onclick="quickAi('${x}')">${x}</button>`).join("")}<p class="muted" style="font-size:.66rem;margin-top:14px">Réponses simulées localement.</p></aside></div>`},
roadmap(){let phases=[["Version 1 — Personnel",["Connexion et rôles","Fiches salariés","Pointage","Planning","Absences"]],["Version 2 — Opérations",["Clients et CRM","Chantiers","Photos","Matériel","Rentabilité"]],["Version 3 — Finance",["Devis","Factures","Paiements","Messagerie","Portail client"]],["Versions futures",["Stock intelligent","Véhicules","Maintenance","IA","Comptabilité","API"]]];return `${section("Versions actuelles et futures","Tous les modules prévus sont représentés.","")}<div class="roadmap section">${phases.map((p,i)=>`<div class="road-col"><div class="card-head"><h4>${p[0]}</h4>${status(i<3?"Intégré":"Prototype")}</div>${p[1].map(x=>`<div class="road-item">${x}</div>`).join("")}</div>`).join("")}</div><article class="card"><div class="card-head"><h3>Automatisations prévues</h3></div><div class="grid g3">${["Rappels de factures","Chantier après signature","Réapprovisionnement","Entretien véhicules","Rapports automatiques","Synchronisation comptable","Signature électronique","Notifications mobiles","API partenaires"].map(x=>`<div class="list-row"><b>${x}</b>${status("Prévu")}</div>`).join("")}</div></article>`},
security(){let roles=["Administrateur","Direction","RH","Responsable","Comptabilité","Salarié","Client"];return `${section("Sécurité et accès","Permissions par rôle, entreprise et donnée.","")}<div class="grid g4 section">${kpi("2FA","Activée","Comptes sensibles","◇")}${kpi("Rôles",roles.length,"Configurés","♟")}${kpi("Sessions","6","4 appareils","◉")}${kpi("Sauvegardes","Quotidiennes","Architecture prévue","↻")}</div><article class="card"><div class="table"><table><thead><tr><th>Rôle</th><th>RH</th><th>Finance</th><th>Chantiers</th><th>Stock</th><th>Clients</th><th>Paramètres</th></tr></thead><tbody>${roles.map((r,i)=>`<tr><td><b>${r}</b></td>${[0,1,2,3,4,5].map(j=>`<td>${status(i===0||i===1?"Autorisé":j===2?"Autorisé":"Limité")}</td>`).join("")}</tr>`).join("")}</tbody></table></div></article>`},
audit(){return `${section("Journal d’activité","Traçabilité des actions.",`<button class="btn secondary" data-action="export-audit">Exporter</button>`)}<article class="card"><div class="table"><table><thead><tr><th>Date</th><th>Utilisateur</th><th>Action</th><th>Objet</th><th>Détail</th></tr></thead><tbody>${db.audit.map(a=>`<tr><td>${a.date}</td><td><b>${a.user}</b></td><td>${status(a.action)}</td><td>${a.object}</td><td>${a.detail}</td></tr>`).join("")}</tbody></table></div></article>`},
settings(){return `${section("Paramètres","Préférences, sauvegardes et données.","")}<div class="grid g2"><article class="card"><div class="card-head"><h3>Préférences</h3></div><label>Thème<select id="setTheme"><option value="dark">Sombre</option><option value="light">Clair</option></select></label><label>Langue<select><option>Français</option><option>English</option><option>Deutsch</option><option>Italiano</option><option>Português</option><option>Español</option><option>Shqip</option></select></label><label><input type="checkbox" checked style="width:auto"> Géolocalisation facultative</label><label><input type="checkbox" checked style="width:auto"> Rappels automatiques</label><button class="btn primary" data-action="save-settings">Enregistrer</button></article><article class="card"><div class="card-head"><h3>Sauvegarde</h3></div><p class="muted" style="font-size:.72rem">Exportez ou restaurez toutes les données locales.</p><button class="btn secondary wide" data-action="backup">Exporter JSON</button><button class="btn secondary wide" style="margin-top:8px" data-action="import">Importer JSON</button><button class="btn danger wide" style="margin-top:8px" data-action="reset">Réinitialiser</button><div class="mini-grid" style="margin-top:14px">${mini("Version",VERSION)}${mini("Stockage","Navigateur")}${mini("Hors ligne","Activé")}${mini("PWA","Installable")}</div></article></div>`}
};
function employeeDash(){let e=emp(4),ps=db.projects.filter(p=>p.team.includes(4));return `<div class="grid g4 section">${kpi("Heures semaine",e.hours+" h","Objectif 42 h","◷")}${kpi("Prochain chantier","08h00","SE-2026-0045","▰")}${kpi("Vacances",e.vacation+" j","Disponibles","☀")}${kpi("Heures sup.","+"+e.overtime+" h","Solde","＋")}</div><div class="grid g2 section"><article class="card clock">${clockBox()}</article><article class="card"><div class="card-head"><h3>Planning du jour</h3></div><div class="timeline"><div class="tl"><span class="dot"></span><div><b>08h00–12h00 · Mme Dupont</b><p>SE-2026-0045</p></div></div><div class="tl"><span class="dot"></span><div><b>13h00–16h30 · Régie Arc</b><p>Contrôle final</p></div></div><div class="tl"><span class="dot"></span><div><b>16h30–17h00 · Dépôt</b><p>Retour matériel</p></div></div></div></article></div><div class="grid g2">${ps.map(projectCard).join("")}</div>`}
function clientDash(){let p=db.projects[0];return `<div class="grid g3 section">${kpi("Chantier",p.id,p.title,"▰")}${kpi("Avancement",p.progress+" %","Aujourd’hui","↗")}${kpi("Prochaine visite","3 août · 08h00","2 techniciens","▦")}</div><div class="grid g2"><article class="card"><div class="card-head"><h3>${p.title}</h3>${status(p.status)}</div><p class="muted">${p.address}</p><div class="progress"><span style="width:${p.progress}%"></span></div><div class="progress-meta"><span>${date(p.start)}</span><span>${date(p.end)}</span></div><div class="timeline" style="margin-top:18px"><div class="tl"><span class="dot"></span><div><b>Tableau remplacé</b><p>Terminé · 6 photos</p></div></div><div class="tl"><span class="dot"></span><div><b>Prises et interrupteurs</b><p>En cours · 70 %</p></div></div><div class="tl"><span class="dot"></span><div><b>Contrôle final</b><p>Prévu le 7 août</p></div></div></div></article><article class="card"><div class="card-head"><h3>Documents récents</h3></div><div class="list">${["Devis signé.pdf","Facture d’acompte.pdf","Rapport d’avancement.pdf","Photos chantier.zip"].map(x=>`<div class="list-row"><div><b>▤ ${x}</b><small>Disponible</small></div><button class="btn small secondary">Ouvrir</button></div>`).join("")}</div></article></div>`}

const actions={
"new-company":()=>form("company"),"new-employee":()=>form("employee"),"new-project":()=>form("project"),"new-client":()=>form("client"),"new-quote":()=>form("quote"),"new-invoice":()=>form("invoice"),"new-payment":()=>form("payment"),"new-expense":()=>form("expense"),"new-stock":()=>form("stock"),"new-supplier":()=>form("supplier"),"new-vehicle":()=>form("vehicle"),"new-tool":()=>form("tool"),"new-maintenance":()=>form("maintenance"),"new-absence":()=>form("absence"),"new-planning":()=>form("planning"),
"clock":()=>{db.clock.active=!db.clock.active;db.clock.break=false;db.clock.project=document.getElementById("clockProject")?.value||db.clock.project;save();audit(db.clock.active?"Début":"Fin","Pointage",db.clock.project);render();toast(db.clock.active?"Journée commencée":"Journée enregistrée")},
"break":()=>{if(!db.clock.active)return toast("Commencez la journée");db.clock.break=!db.clock.break;save();render();toast(db.clock.break?"Pause commencée":"Travail repris")},
"approve-time":()=>{db.time.forEach(t=>t.status="Validé");save();audit("Validation","Pointages","Semaine validée");render();toast("Heures validées")},
"send-message":()=>{let i=document.getElementById("messageText");if(!i.value.trim())return;db.messages.push({id:Date.now(),sender:profiles[session.role].name,kind:"us",text:i.value.trim(),time:new Date().toLocaleTimeString("fr-CH",{hour:"2-digit",minute:"2-digit"})});save();render();toast("Message envoyé")},
"ask-ai":()=>{let i=document.getElementById("aiInput");if(i.value.trim())quickAi(i.value.trim())},
"export-report":()=>exportRows("rapport",[["Chantier","Budget","Coût","Marge"],...db.projects.map(p=>[p.id,p.budget,p.cost,p.budget-p.cost])]),
"export-employees":()=>exportRows("salaries",[["Nom","Fonction","Entreprise","Heures","Vacances"],...db.employees.map(e=>[e.name,e.job,comp(e.company).name,e.hours,e.vacation])]),
"export-time":()=>exportRows("heures",[["Date","Salarié","Chantier","Début","Fin","Total"],...db.time.map(t=>[t.date,emp(t.employeeId).name,t.project,t.start,t.end,t.hours])]),
"export-planning":()=>toast("Planning exporté"),
"export-projects":()=>exportRows("chantiers",[["Numéro","Client","Titre","Statut","Budget","Coût"],...db.projects.map(p=>[p.id,cli(p.clientId).name,p.title,p.status,p.budget,p.cost])]),
"export-clients":()=>exportRows("clients",[["Client","Type","E-mail","Téléphone","Ville","CA"],...db.clients.map(c=>[c.name,c.type,c.email,c.phone,c.city,c.revenue])]),
"export-quotes":()=>exportRows("devis",[["Numéro","Client","Montant","Statut"],...db.quotes.map(q=>[q.id,cli(q.clientId).name,q.amount,q.status])]),
"export-invoices":()=>exportRows("factures",[["Numéro","Client","Montant","Payé","Statut"],...db.invoices.map(i=>[i.id,cli(i.clientId).name,i.amount,i.paid,i.status])]),
"export-expenses":()=>exportRows("depenses",[["Référence","Fournisseur","Chantier","Montant"],...db.expenses.map(e=>[e.id,e.supplier,e.project,e.amount])]),
"export-stock":()=>exportRows("stock",[["Référence","Article","Stock","Minimum"],...db.inventory.map(i=>[i.sku,i.name,i.stock,i.min])]),
"export-audit":()=>exportRows("journal",[["Date","Utilisateur","Action","Objet","Détail"],...db.audit.map(a=>[a.date,a.user,a.action,a.object,a.detail])]),
"backup":backup,"import":()=>document.getElementById("importFile").click(),"reset":()=>{if(confirm("Réinitialiser toutes les données ?")){reset();shell();toast("Données réinitialisées")}},
"save-settings":()=>{db.settings.theme=document.getElementById("setTheme").value;save();theme();toast("Paramètres enregistrés")}
};
function exportRows(n,r){download(`Sousa_Group_One_${n}.csv`,"\ufeff"+csv(r),"text/csv;charset=utf-8");toast("Export créé")}
function backup(){download(`Sousa_Group_One_sauvegarde_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db,null,2),"application/json");toast("Sauvegarde exportée")}
function importBackup(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.projects)throw Error();db=d;save();shell();toast("Sauvegarde restaurée")}catch(x){alert("Fichier invalide")}};r.readAsText(f);e.target.value=""}
function quickAi(prompt){db.ai.push({role:"user",text:prompt});let p=prompt.toLowerCase(),a;if(p.includes("stock")){let l=db.inventory.filter(x=>x.stock<=x.min);a=`${l.length} stocks faibles : ${l.map(x=>`${x.name} (${x.stock} ${x.unit})`).join(", ")}. Une commande fournisseur est recommandée.`}else if(p.includes("se-2026-0045")||p.includes("résume")){let x=db.projects[0];a=`Le chantier ${x.id} est à ${x.progress} %. ${x.hours} heures ont été enregistrées. Budget : ${money(x.budget)}. Coût actuel : ${money(x.cost)}.`}else if(p.includes("facture")){let l=db.invoices.filter(x=>x.status==="En retard");a=`${l.length} facture à relancer : ${l.map(x=>`${x.id}, ${cli(x.clientId).name}, ${money(x.amount)}`).join("; ")}.`}else if(p.includes("heure")){let total=db.employees.reduce((a,b)=>a+b.overtime,0);a=`Le solde d’heures supplémentaires est de ${total.toFixed(2)} h. Joao Sousa et Lucas Moreira ont les soldes les plus élevés.`}else if(p.includes("rapport"))a="Rapport proposé : travaux réalisés, avancement, photos, prochaines étapes, changements validés et date estimée de fin.";else a="J’ai analysé les données locales. La version de production pourra utiliser une véritable IA sécurisée.";db.ai.push({role:"assistant",text:a});save();render()}
function approveAbsence(id){let a=db.absences.find(x=>x.id===id);modal("Traiter la demande",`<p><b>${emp(a.employeeId).name}</b> demande ${a.days} jour(s) de ${a.type.toLowerCase()}.</p><div class="form-actions"><button class="btn danger" onclick="setAbsence(${id},'Refusée')">Refuser</button><button class="btn primary" onclick="setAbsence(${id},'Approuvée')">Approuver</button></div>`)}
function setAbsence(id,s){db.absences.find(x=>x.id===id).status=s;save();audit("Validation","Absence",s);closeModal();render();toast("Demande "+s.toLowerCase())}
function form(type){let co=db.companies.filter(c=>c.id!=="group").map(c=>({value:c.id,label:c.name})),cl=db.clients.map(c=>({value:c.id,label:c.name})),em=db.employees.map(e=>({value:e.id,label:e.name})),t,h;
if(type==="company"){t="Nouvelle entreprise";h=field("Nom","f_name")+field("Code","f_code")+field("Secteur","f_type")}
if(type==="employee"){t="Nouveau salarié";h=field("Nom","f_name")+field("Fonction","f_job")+field("Entreprise","f_company","text","",false,co)+field("E-mail","f_email","email")+field("Téléphone","f_phone","tel")+field("Salaire","f_salary","number")+field("Taux d’activité","f_activity","number","100")+field("Date d’entrée","f_entry","date")}
if(type==="project"){t="Nouveau chantier";h=field("Titre","f_title")+field("Entreprise","f_company","text","",false,co)+field("Client","f_client","text","",false,cl)+field("Adresse","f_address","text","",true)+field("Début","f_start","date")+field("Fin","f_end","date")+field("Budget","f_budget","number")+area("Description","f_desc")}
if(type==="client"){t="Nouveau client";h=field("Nom","f_name")+field("Type","f_type")+field("E-mail","f_email","email")+field("Téléphone","f_phone","tel")+field("Ville","f_city")}
if(type==="quote"){t="Nouveau devis";h=field("Client","f_client","text","",false,cl)+field("Objet","f_title")+field("Montant","f_amount","number")+field("Validité","f_valid","date")}
if(type==="invoice"){t="Nouvelle facture";h=field("Client","f_client","text","",false,cl)+field("Chantier","f_project")+field("Objet","f_title")+field("Montant","f_amount","number")+field("Échéance","f_due","date")}
if(type==="payment"){t="Nouveau paiement";h=field("Facture","f_invoice")+field("Client","f_client","text","",false,cl)+field("Montant","f_amount","number")+field("Date","f_date","date")+field("Mode","f_method","text","Virement")}
if(type==="expense"){t="Nouvelle dépense";h=field("Entreprise","f_company","text","",false,co)+field("Fournisseur","f_supplier")+field("Chantier","f_project")+field("Montant","f_amount","number")+field("Date","f_date","date")}
if(type==="stock"){t="Nouvel article";h=field("Référence","f_sku")+field("Nom","f_name")+field("Catégorie","f_category")+field("Stock","f_stock","number")+field("Minimum","f_min","number")+field("Unité","f_unit","text","pcs")+field("Achat","f_buy","number")+field("Vente","f_sell","number")}
if(type==="supplier"){t="Nouveau fournisseur";h=field("Nom","f_name")+field("Catégorie","f_category")+field("Contact","f_contact")+field("E-mail","f_email","email")+field("Téléphone","f_phone","tel")}
if(type==="vehicle"){t="Nouveau véhicule";h=field("Référence","f_id")+field("Plaque","f_plate")+field("Marque","f_brand")+field("Modèle","f_model")+field("Entreprise","f_company","text","",false,co)+field("Conducteur","f_driver","text","",false,em)+field("Kilométrage","f_km","number")}
if(type==="tool"){t="Nouvel outil";h=field("Référence","f_id")+field("Nom","f_name")+field("Catégorie","f_category")+field("N° série","f_serial")+field("Entreprise","f_company","text","",false,co)+field("Attribué à","f_assigned","text","",false,em)}
if(type==="maintenance"){t="Nouveau contrat";h=field("Client","f_client","text","",false,cl)+field("Titre","f_title")+field("Entreprise","f_company","text","",false,co)+field("Fréquence","f_frequency","text","Mensuelle")+field("Prochaine visite","f_next","date")+field("Valeur annuelle","f_amount","number")}
if(type==="absence"){t="Nouvelle demande";h=field("Salarié","f_employee","text","",false,em)+field("Type","f_type","text","Vacances")+field("Du","f_from","date")+field("Au","f_to","date")+area("Commentaire","f_comment")}
if(type==="planning"){t="Planifier";h=field("Chantier","f_project")+field("Salarié","f_employee","text","",false,em)+field("Date","f_date","date")+field("Début","f_start","time")+field("Fin","f_end","time")+field("Lieu","f_location")}
modal(t,`<div class="form-grid">${h}</div>${formBtns(`saveEntity('${type}')`)}`)}
function saveEntity(type){let now=new Date().toISOString().slice(0,10);
if(type==="company")db.companies.push({id:val("f_code").toLowerCase(),code:val("f_code"),name:val("f_name"),type:val("f_type"),employees:0});
if(type==="employee")db.employees.push({id:Date.now(),name:val("f_name"),initials:val("f_name").split(" ").map(x=>x[0]).join("").slice(0,2),job:val("f_job"),company:val("f_company"),email:val("f_email"),phone:val("f_phone"),salary:+val("f_salary"),activity:+val("f_activity"),status:"Présent",hours:0,overtime:0,vacation:20,entry:val("f_entry"),vehicle:""});
if(type==="project"){let c=comp(val("f_company"));db.projects.push({id:`${c.code}-${new Date().getFullYear()}-${String(db.projects.length+1).padStart(4,"0")}`,company:c.id,clientId:+val("f_client"),title:val("f_title"),address:val("f_address"),team:[],status:"Nouveau",progress:0,start:val("f_start"),end:val("f_end"),budget:+val("f_budget"),cost:0,hours:0,materials:0,photos:0,docs:0,description:val("f_desc")})}
if(type==="client")db.clients.push({id:Date.now(),name:val("f_name"),type:val("f_type"),email:val("f_email"),phone:val("f_phone"),city:val("f_city"),status:"Prospect",projects:0,revenue:0});
if(type==="quote")db.quotes.push({id:`D-${new Date().getFullYear()}-${String(db.quotes.length+112).padStart(4,"0")}`,clientId:+val("f_client"),title:val("f_title"),amount:+val("f_amount"),status:"Brouillon",date:now,valid:val("f_valid")});
if(type==="invoice")db.invoices.push({id:`F-${new Date().getFullYear()}-${String(db.invoices.length+89).padStart(4,"0")}`,clientId:+val("f_client"),project:val("f_project"),title:val("f_title"),amount:+val("f_amount"),paid:0,status:"Brouillon",date:now,due:val("f_due")});
if(type==="payment")db.payments.push({id:`P-${new Date().getFullYear()}-${String(db.payments.length+62).padStart(4,"0")}`,invoice:val("f_invoice"),clientId:+val("f_client"),amount:+val("f_amount"),date:val("f_date"),method:val("f_method"),status:"Confirmé"});
if(type==="expense")db.expenses.push({id:`A-${new Date().getFullYear()}-${String(db.expenses.length+107).padStart(4,"0")}`,company:val("f_company"),supplier:val("f_supplier"),project:val("f_project"),amount:+val("f_amount"),date:val("f_date"),category:"Matériel",status:"À valider"});
if(type==="stock")db.inventory.push({id:Date.now(),sku:val("f_sku"),name:val("f_name"),category:val("f_category"),stock:+val("f_stock"),min:+val("f_min"),unit:val("f_unit"),buy:+val("f_buy"),sell:+val("f_sell"),location:"Dépôt"});
if(type==="supplier")db.suppliers.push({id:Date.now(),name:val("f_name"),category:val("f_category"),contact:val("f_contact"),email:val("f_email"),phone:val("f_phone"),rating:4,spend:0});
if(type==="vehicle")db.vehicles.push({id:val("f_id"),plate:val("f_plate"),brand:val("f_brand"),model:val("f_model"),company:val("f_company"),driver:+val("f_driver"),km:+val("f_km"),status:"Disponible",service:""});
if(type==="tool")db.tools.push({id:val("f_id"),name:val("f_name"),category:val("f_category"),serial:val("f_serial"),company:val("f_company"),assigned:+val("f_assigned"),status:"Attribué",check:""});
if(type==="maintenance")db.maintenance.push({id:`CTR-${String(db.maintenance.length+1).padStart(3,"0")}`,clientId:+val("f_client"),title:val("f_title"),company:val("f_company"),frequency:val("f_frequency"),next:val("f_next"),amount:+val("f_amount"),status:"Proposé"});
if(type==="absence"){let f=new Date(val("f_from")),t=new Date(val("f_to")),days=Math.max(1,Math.round((t-f)/86400000)+1);db.absences.push({id:Date.now(),employeeId:+val("f_employee"),type:val("f_type"),from:val("f_from"),to:val("f_to"),days,status:"En attente",comment:val("f_comment")})}
save();audit("Création",type,"Nouvel élément");closeModal();render();toast("Élément créé")}
function openEmployee(id){let e=emp(id);modal("Fiche salarié · "+e.name,`<div class="detail"><div class="detail-avatar">${e.initials}</div><div><h3>${e.name}</h3><p class="muted">${e.job} · ${comp(e.company).name}</p></div></div><div class="tabs"><button class="tab active">Résumé</button><button class="tab">Contrat</button><button class="tab">Heures</button><button class="tab">Absences</button><button class="tab">Documents</button></div><div class="mini-grid">${mini("E-mail",e.email)}${mini("Téléphone",e.phone)}${mini("Activité",e.activity+" %")}${mini("Salaire",money(e.salary))}${mini("Heures",e.hours+" h")}${mini("Heures sup.",e.overtime+" h")}${mini("Vacances",e.vacation+" j")}${mini("Véhicule",e.vehicle||"Aucun")}</div>`)}
function openClient(id){let c=cli(id),ps=db.projects.filter(p=>p.clientId===id);modal("Client · "+c.name,`<div class="detail"><div class="detail-avatar">${c.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><h3>${c.name}</h3><p class="muted">${c.type} · ${c.city}</p></div></div><div class="mini-grid">${mini("E-mail",c.email)}${mini("Téléphone",c.phone)}${mini("Chantiers",ps.length)}${mini("CA",money(c.revenue))}</div><div class="list" style="margin-top:14px">${ps.map(p=>`<div class="list-row"><div><b>${p.id}</b><small>${p.title}</small></div>${status(p.status)}</div>`).join("")}</div>`)}
function openProject(id){let p=db.projects.find(x=>x.id===id);modal(`${p.id} · ${cli(p.clientId).name}`,`<div class="tabs"><button class="tab active">Résumé</button><button class="tab">Équipe</button><button class="tab">Heures</button><button class="tab">Matériel</button><button class="tab">Photos</button><button class="tab">Documents</button><button class="tab">Finance</button></div><div class="grid g2"><div class="mini-grid">${mini("Entreprise",comp(p.company).name)}${mini("Statut",p.status)}${mini("Début",date(p.start))}${mini("Fin",date(p.end))}${mini("Budget",money(p.budget))}${mini("Coût",money(p.cost))}${mini("Marge",money(p.budget-p.cost))}${mini("Heures",p.hours+" h")}</div><div><h4>Avancement</h4><div class="progress"><span style="width:${p.progress}%"></span></div><p class="muted" style="font-size:.7rem;margin-top:14px">${p.description}</p></div></div><div class="grid g3" style="margin-top:14px">${mini("Matériel",p.materials)}${mini("Photos",p.photos)}${mini("Documents",p.docs)}</div>`)}
function openDoc(id,kind){let d=kind==="quote"?db.quotes.find(x=>x.id===id):db.invoices.find(x=>x.id===id),c=cli(d.clientId);modal(`${kind==="quote"?"Devis":"Facture"} ${id}`,`<div class="doc-actions"><button class="btn secondary" onclick="window.print()">Imprimer / PDF</button>${kind==="quote"&&session.role==="client"?`<button class="btn primary" onclick="acceptQuote('${id}')">Accepter et signer</button>`:""}</div><div class="document"><div class="document-head"><div><h2>SOUSA GROUP</h2><p>Sousa Électricité · Sousa Home Service · Sousa Tech</p></div><div><b>${kind==="quote"?"DEVIS":"FACTURE"}</b><br>${id}<br>${date(d.date)}</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:30px;margin:28px 0"><div><b>Émetteur</b><p>Sousa Group<br>Vaud, Suisse</p></div><div><b>Client</b><p>${c.name}<br>${c.city}<br>${c.email}</p></div></div><table><thead><tr><th>Description</th><th>Qté</th><th>Prix</th><th>Total</th></tr></thead><tbody><tr><td>${d.title}</td><td>1</td><td>${money(d.amount)}</td><td>${money(d.amount)}</td></tr></tbody></table><div class="doc-total"><b>Total TTC : ${money(d.amount)}</b></div></div>`)}
function acceptQuote(id){db.quotes.find(x=>x.id===id).status="Accepté";save();audit("Signature","Devis "+id,"Accepté");closeModal();render();toast("Devis accepté")}
window.closeModal=closeModal;window.session=session;window.nav=nav;window.render=render;window.saveEntity=saveEntity;window.approveAbsence=approveAbsence;window.setAbsence=setAbsence;window.quickAi=quickAi;window.acceptQuote=acceptQuote;window.readNotifications=readNotifications;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;document.getElementById("installBtn").classList.remove("hidden")});document.getElementById("installBtn").onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;document.getElementById("installBtn").classList.add("hidden")}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
